name: Dependabot

on:
  schedule:
    - cron: '0 0 * * 0'  # Weekly on Sundays
  workflow_dispatch:

permissions:
  contents: write
  pull-requests: write

jobs:
  dependabot:
    runs-on: ubuntu-latest
    steps:
      - name: Dependabot
        uses: dependabot/dependabot-core@main
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          directory: /
          package-manager: cargo